services:
  app:
    build: .
    ports:
      - "19000:19000" 
      - "19001:19001"
      - "19002:19002" 
    volumes:
      - .:/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0  
